import {
  ArrowRight,
  ChevronRight,
  Droplet,
  Flower2,
  Heart,
  Home,
  Lock,
  Menu,
  Moon,
  Play,
  Plus,
  Quote,
  Search,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Truck,
  type LucideProps,
  User,
  Wind,
  X,
  Zap,
} from '@/components/ui/icon';

// Storefront `Icon.*` set, now backed by Lucide (docs/design/icon-system.md).
// Keys are frozen so existing call sites keep working; new code should import
// from '@/components/ui/icon' directly.
type P = LucideProps;

export const Icon = {
  // Key frozen for call-site compat; renders Flower2 (leaf/sprout glyphs retired).
  leaf: (p: P) => <Flower2 {...p} />,
  truck: (p: P) => <Truck {...p} />,
  shield: (p: P) => <ShieldCheck {...p} />,
  star: (p: P) => <Star fill="currentColor" strokeWidth={0} {...p} />,
  arrow: (p: P) => <ArrowRight {...p} />,
  bag: (p: P) => <ShoppingBag {...p} />,
  menu: (p: P) => <Menu {...p} />,
  x: (p: P) => <X {...p} />,
  play: (p: P) => <Play fill="currentColor" {...p} />,
  droplet: (p: P) => <Droplet {...p} />,
  sun: (p: P) => <Sun {...p} />,
  spark: (p: P) => <Sparkles {...p} />,
  quote: (p: P) => <Quote fill="currentColor" strokeWidth={0} {...p} />,
  user: (p: P) => <User {...p} />,
  truckFast: (p: P) => <Truck {...p} />,
  lock: (p: P) => <Lock {...p} />,
  chevron: (p: P) => <ChevronRight {...p} />,
  heart: (p: P) => <Heart {...p} />,
  plus: (p: P) => <Plus {...p} />,
  search: (p: P) => <Search {...p} />,
  wind: (p: P) => <Wind {...p} />,
  moon: (p: P) => <Moon {...p} />,
  home: (p: P) => <Home {...p} />,
  zap: (p: P) => <Zap {...p} />,
  sprout: (p: P) => <Flower2 {...p} />,
};
