import {
  ArrowRight,
  Dot,
  Flask,
  LayoutGrid,
  CalendarDays,
  Earth,
  Leaf,
  PawPrint,
  PottedPlant,
  Ruler,
  Scissors,
  Shovel,
  Sprout,
  Thermometer,
  TrendingUp,
  Droplets,
  Flower,
  ChevronRight,
  Droplet,
  Flower2,
  Heart,
  Home,
  Lock,
  Menu,
  Moon,
  Play,
  Plus,
  Quote,
  Search,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Truck,
  type LucideProps,
  User,
  Wind,
  X,
  Zap,
} from '@/components/ui/icon';

// Storefront `Icon.*` set, now backed by Lucide (docs/design/icon-system.md).
// Keys are frozen so existing call sites keep working; new code should import
// from '@/components/ui/icon' directly.
type P = LucideProps;

export const Icon = {
  // Keys are frozen for call-site compat, but each now resolves to a DISTINCT
  // glyph. They used to all render Flower2, which is why five different plant
  // specs looked identical on the product page.
  leaf: (p: P) => <Leaf {...p} />,
  truck: (p: P) => <Truck {...p} />,
  shield: (p: P) => <ShieldCheck {...p} />,
  star: (p: P) => <Star fill="currentColor" strokeWidth={0} {...p} />,
  arrow: (p: P) => <ArrowRight {...p} />,
  bag: (p: P) => <ShoppingBag {...p} />,
  menu: (p: P) => <Menu {...p} />,
  x: (p: P) => <X {...p} />,
  play: (p: P) => <Play fill="currentColor" {...p} />,
  droplet: (p: P) => <Droplet {...p} />,
  sun: (p: P) => <Sun {...p} />,
  spark: (p: P) => <Sparkles {...p} />,
  quote: (p: P) => <Quote fill="currentColor" strokeWidth={0} {...p} />,
  user: (p: P) => <User {...p} />,
  truckFast: (p: P) => <Truck {...p} />,
  lock: (p: P) => <Lock {...p} />,
  chevron: (p: P) => <ChevronRight {...p} />,
  heart: (p: P) => <Heart {...p} />,
  plus: (p: P) => <Plus {...p} />,
  search: (p: P) => <Search {...p} />,
  wind: (p: P) => <Wind {...p} />,
  moon: (p: P) => <Moon {...p} />,
  home: (p: P) => <Home {...p} />,
  zap: (p: P) => <Zap {...p} />,
  sprout: (p: P) => <Sprout {...p} />,
  flower: (p: P) => <Flower {...p} />,
  plant: (p: P) => <PottedPlant {...p} />,
  // plant-domain concepts that previously borrowed a generic glyph
  thermometer: (p: P) => <Thermometer {...p} />,
  calendar: (p: P) => <CalendarDays {...p} />,
  growth: (p: P) => <TrendingUp {...p} />,
  ruler: (p: P) => <Ruler {...p} />,
  earth: (p: P) => <Earth {...p} />,
  paw: (p: P) => <PawPrint {...p} />,
  soil: (p: P) => <Shovel {...p} />,
  prune: (p: P) => <Scissors {...p} />,
  humidity: (p: P) => <Droplets {...p} />,
  // neutral marks -- deliberately NOT botanical, so a leaf never stands in
  // as pure ornament (owner rule: a leaf means a plant, nothing else).
  dot: (p: P) => <Dot {...p} />,
  flask: (p: P) => <Flask {...p} />,
  grid: (p: P) => <LayoutGrid {...p} />,
};
